# Generated by Django 4.0.6 on 2022-07-30 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_kor', models.CharField(max_length=100, null=True)),
                ('title_eng', models.CharField(max_length=100, null=True)),
                ('poster_url', models.URLField(max_length=100, null=True)),
                ('rating_aud', models.CharField(max_length=100, null=True)),
                ('rating_cri', models.CharField(max_length=100, null=True)),
                ('genre', models.CharField(max_length=100, null=True)),
                ('showtimes', models.CharField(max_length=100, null=True)),
                ('release_date', models.CharField(max_length=100, null=True)),
                ('rate', models.CharField(max_length=100, null=True)),
                ('summary', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('role', models.CharField(max_length=100, null=True)),
                ('image_url', models.CharField(max_length=100, null=True)),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.movie')),
            ],
        ),
    ]
