# Generated by Django 4.0.6 on 2022-07-30 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_remove_movie_image_url_remove_movie_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Staff',
            new_name='Stafff',
        ),
    ]
