# Generated by Django 4.0.6 on 2022-07-30 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_rename_staff_stafff'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stafff',
            new_name='Staff',
        ),
    ]
